
trigger:
  - main

parameters:
  - name: action
    displayName: |
      üîß A√ß√£o a ser executada no Terraform onde : 
      - plan:
         Gera um plano de execu√ß√£o, mostrando quais a√ß√µes ser√£o tomadas sem fazer nenhuma altera√ß√£o.
      - apply:
         Executa as a√ß√µes propostas no plano, fazendo altera√ß√µes na infraestrutura.
      - destroy:
         Remove todos os recursos gerenciados pela configura√ß√£o, desmontando efetivamente a infraestrutura.
      - none:
         Indica que nenhuma a√ß√£o deve ser tomada.
      - run-all:
         Executa as a√ß√µes de plano e aplica√ß√£o para todas as configura√ß√µes.
      - apply-target:
         Aplica mudan√ßas a um alvo espec√≠fico dentro da configura√ß√£o.    
      > Aviso: A op√ß√£o "run-all" executar√° a a√ß√£o em todos os m√≥dulos do projeto e pode comprometer a infra ## - üè¥‚Äç‚ò†Ô∏è - MUITO CUIDADO # 
    default: none
    type: string
    values:
      - plan
      - apply
      - destroy
      - none
      - run-all
      - apply-target

  - name: terraform_version
    displayName: üåç Vers√£o do Terraform
    default: 1.10.5
    type: string
    values:
      - latest
      - 1.10.5
      - 1.9.8

  - name: terragrunt_version
    displayName: üåç Vers√£o do Terragrunt
    default: 0.67.9
    type: string
    values:
      - latest
      - 0.31.8
      - 0.31.7
      - 0.67.9

  - name: environment
    displayName: üåê Qual ambiente vai rodar
    default: az-csh-dev
    type: string
    values:
      - az-csh-dev
      - az-csh-prod

  - name: resource
    displayName: |
      üõ†Ô∏è Recurso alvo do projeto Terragrunt ||
      Equivalente ao -c no script de deploy que aponta o recurso:
      app, networking, resource-group, etc.
      > Aviso: Se a op√ß√£o de deploy de todos os recursos abaixo for escolhida, 
      este par√¢metro ser√° ignorado e pode conter qualquer valor.
    type: string
    values:
      - app
      - networking
      - resource-group
      - storage
      - vnet
      - vm
      - jenkins
      - prometheus

  - name: geo_location
    displayName: üåç Localiza√ß√£o dentro do projeto Terraform (n√£o equivale ao "location" do Azure)
    default: 'us'
    type: string
    values:
      - 'us'
      - 'br'
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: csh-terragrunt-environments
  - name: environment
    value: ${{ parameters.environment }}
  - name: resource
    value: ${{ parameters.resource }}
  - name: geo_location
    value: ${{ parameters.geo_location }}
  - name: STORAGE_ACCOUNT_NAME
    value: tfstatecsh
  - name: CONTAINER_NAME
    value: tfstate
  - name: RESOURCE_GROUP_NAME
    value: terraform-state-csh

jobs:
  - job: "TerragruntWorkflow"
    displayName: 'üöÄ - Fluxo de Trabalho do Terragrunt'
    

    steps:
      - bash: |
          echo "##vso[task.setvariable variable=AgentName;isoutput=true]$(Agent.Name)"
        name: passOutput
        displayName: 'üñ•Ô∏è - Capturar Nome do Agente'

      - task: DownloadSecureFile@1
        name: downloadPrivateKey
        displayName: 'Download Private SSH Key'
        inputs:
          secureFile: 'id_rsa'

      - task: DownloadSecureFile@1
        name: downloadPublicKey
        displayName: 'Download Public SSH Key'
        inputs:
          secureFile: 'id_rsa.pub'
          displayName: 'üîë - Baixando Chave SSH'

      - script: |
          # Criar o diret√≥rio .ssh se n√£o existir
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Adicionar a chave privada e p√∫blica
          cp $(downloadPrivateKey.secureFilePath) ~/.ssh/id_rsa
          cp $(downloadPublicKey.secureFilePath) ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub

          # Adicionar dev.azure.com ao known_hosts
          ssh-keyscan -H dev.azure.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          # Criar o arquivo de configura√ß√£o do SSH e desabilitar host key checking
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config
        displayName: 'üîë - Instalar Chave SSH'
   
      # - task: InstallSSHKey@0
      #   inputs:
      #     knownHostsEntry: 'dev.azure.com'
      #     sshKeySecureFile: 'id_rsa.pub'
      #     displayName: 'üîë - Instalar Chave SSH'
      
      - script: |
          sudo apt update
          sudo apt install -y git curl wget unzip jq
        displayName: 'üßë‚Äçüîß - Instalar Pr√©-requisitos'

      - script: |
          set -e
          # Instalar tfenv e Terraform
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
          mkdir -p ~/.local/bin/
          . ~/.profile
          ln -s ~/.tfenv/bin/* ~/.local/bin
          tfenv install ${{ parameters.terraform_version }}
          tfenv use ${{ parameters.terraform_version }}

          # Instalar Terragrunt
          curl -L -o /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ parameters.terragrunt_version }}/terragrunt_linux_amd64
          chmod +x /usr/local/bin/terragrunt

          # Verificar instala√ß√£o correta do Terraform
          terraform --version | grep "${{ parameters.terraform_version }}" || { echo "Erro: Terraform n√£o instalado corretamente!"; exit 1; }

          # Verificar instala√ß√£o correta do Terragrunt
          terragrunt --version | grep "${{ parameters.terragrunt_version }}" || { echo "Erro: Terragrunt n√£o instalado corretamente!"; exit 1; }

          echo "Terraform e Terragrunt instalados corretamente."
        displayName: 'üåé - Instalar Terraform e Terragrunt'
        
      - bash: |
          az login --service-principal \
          --username $ARM_CLIENT_ID \
          --password $ARM_CLIENT_SECRET \
          --tenant $ARM_TENANT_ID
          az account set --subscription $ARM_SUBSCRIPTION_ID
          echo "Login no Azure realizado com sucesso."
        displayName: "\U0001F510 - Login no Azure"

      - script: |
          
          echo "üöÄ - Testando Terragrunt em todo projeto" 
          echo "ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)"
          echo "ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)"
          echo "ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)"
          echo "STA_ACCESS_KEY: $(STA_ACCESS_KEY)"
          echo "ARM_CLIENT_ID: $(ARM_CLIENT_ID)"
          echo "ARM_TENANT_ID: $(ARM_TENANT_ID)"
          ACCOUNT_KEY=$(az storage account keys list --resource-group $(RESOURCE_GROUP_NAME) --account-name $(STORAGE_ACCOUNT_NAME) --query '[0].value' -o tsv)

          cd environments/${{ parameters.environment }}/${{ parameters.geo_location }}
          if [ "${{ parameters.action }}" == "plan" ]; then
            
            echo "üìã - Gerando plano de execu√ß√£o no ambiente ${{ parameters.environment }} e localiza√ß√£o ${{ parameters.geo_location }}"
            terragrunt run-all plan --terragrunt-non-interactive --terragrunt-no-color
          
          elif [ "${{ parameters.action }}" == "apply" ]; then
          
            echo "üöÄ - Aplicando mudan√ßas no ambiente ${{ parameters.environment }} e localiza√ß√£o ${{ parameters.geo_location }}"
            cd environments/"${{ parameters.environment }}"/"${{ parameters.geo_location }}"
            terragrunt run-all apply --terragrunt-non-interactive --terragrunt-no-color
          
          elif [ "${{ parameters.action }}" == "destroy" ]; then
          
            echo "üí£ - Destruindo recursos no ambiente ${{ parameters.environment }} e localiza√ß√£o ${{ parameters.geo_location }}"
            terragrunt run-all destroy --terragrunt-non-interactive --terragrunt-no-color
          
          elif [ "${{ parameters.action }}" == "run-all" ]; then
          
            echo "üîÑ - Executando todas as a√ß√µes no ambiente"
             scripts/deploy.sh  -e az-csh-dev -s us
          
          else
          
            echo "‚ö†Ô∏è - Nada a deployar, a√ß√£o definida foi: ${{ parameters.action }}"
            exit 1
          
          fi    
        displayName: 'üöÄ - Executar A√ß√£o do Terragrunt'

      # # - script: |
      # #     RESOURCE_GROUP_NAME=terraform-state-csh
      # #       STORAGE_ACCOUNT_NAME=tfstatecsh
      # #       CONTAINER_NAME=tfstate
      # #       ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
      # #       export ARM_CLIENT_ID=$ARM_CLIENT_ID
      # #       export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
      # #       export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
      # #       export ARM_TENANT_ID=$ARM_TENANT_ID
      # #     terragrunt --terragrunt-no-color run-all validate \
      # #     --terragrunt-working-dir environments/${{ parameters.environment }}/${{ parameters.geo_location }} \
      # #     --terragrunt-include-external-dependencies \
      # #     --terragrunt-non-interactive
      # #   displayName: '‚úÖ - Validar Configura√ß√£o do Terragrunt'
       

      # # - script: |
      # #     terragrunt run-all plan \
      # #     --terragrunt-working-dir environments/${{ parameters.environment }}/${{ parameters.geo_location }}/${{ parameters.resource }} \
      # #     --terragrunt-include-external-dependencies \
      # #     --terragrunt-non-interactive
      # #   displayName: 'üìã - Gerar Plano de Execu√ß√£o do Terragrunt'
      # #   condition: eq('${{ parameters.action }}', 'plan')

      # # - script: |
      # #       RESOURCE_GROUP_NAME=terraform-state-csh
      # #       STORAGE_ACCOUNT_NAME=tfstatecsh
      # #       CONTAINER_NAME=tfstate
      # #       ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
      # #       export ARM_CLIENT_ID=$ARM_CLIENT_ID
      # #       export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
      # #       export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
      # #       export ARM_TENANT_ID=$ARM_TENANT_ID          
      # #       scripts/deploy.sh  -e "${{ parameters.environment }}" -s "${{ parameters.geo_location }}""
      # #   displayName: 'üöÄ - Aplicar Mudan√ßas com Terragrunt'
      # #   condition: eq('${{ parameters.action }}', 'apply')

      # # - script: |
      # #       RESOURCE_GROUP_NAME=terraform-state-csh
      # #       STORAGE_ACCOUNT_NAME=tfstatecsh
      # #       CONTAINER_NAME=tfstate
      # #       ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
      # #       export ARM_CLIENT_ID=$ARM_CLIENT_ID
      # #       export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
      # #       export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
      # #       export ARM_TENANT_ID=$ARM_TENANT_ID     
      # #       scripts/deploy.sh  -e "${{ parameters.environment }}" -s ${{ parameters.geo_location }}
      # #   displayName: 'üöÄ - Aplicar Mudan√ßas com Terragrunt'
      # #   condition: and(eq('${{ parameters.action }}', 'apply') , eq('${{ parameters.deploy_all_resources }}', true))